services:
  torrentify:
    image: thimble9057/torrentify:latest
    container_name: torrentify
    restart: unless-stopped
    
    user: "1000:1000"

    environment:
      # Activation des médias
      ENABLE_FILMS: "true"
      ENABLE_SERIES: "false"
      ENABLE_MUSIQUES: "true"


      # TMDb
      TMDB_API_KEY: votre_cle_tmdb

      # Trackers (séparés par virgules)
      TRACKERS: https://tracker1/announce,https://tracker2/announce

      # Répertoires sources multiples (optionnel, séparés par virgules)
      # Si non défini, utilise les chemins par défaut : /films, /series, /musiques
      # FILMS_DIRS: "/films,/films-4k"
      # SERIES_DIRS: "/series,/series-4k"
      # MUSIQUES_DIRS: "/musiques"

      # Optionnel
      PARALLEL_JOBS: 1

    volumes:
      # Entrées
      - /mnt/user/data/films:/films
      - /mnt/user/data/series:/series
      - /mnt/user/data/musiques:/musiques
      # Entrées supplémentaires (décommenter si multi-répertoire)
      # - /mnt/user/data/films-4k:/films-4k
      # - /mnt/user/data/series-4k:/series-4k

      # Sorties
      - /mnt/user/data/torrent:/data
